server:
  port: 28921

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:28921
      registerWithEureka: true
      fetchRegistry: false

# apollo配置


#  instance:
#     preferIpAddress: true
#     instance-id: http://localhost:28921
#     hostname: eureka1


